/**
 * Script to add more content items to Supabase
 * Run with: npx tsx scripts/add-more-content.ts
 */

import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://sqesgghvaazyajzjkoap.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxZXNnZ2h2YWF6eWFqemprb2FwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzUxMzgwOSwiZXhwIjoyMDg5MDg5ODA5fQ.UvbRfWU9seJPT9lyCyLmpD4uZrP9jXzsNoeSAjT9HnI'
)

// --- Helpers ---

async function getCategoryId(slug: string): Promise<string> {
  const { data, error } = await supabase.from('categories').select('id').eq('slug', slug).single()
  if (error) throw new Error(`Category "${slug}" not found: ${error.message}`)
  return data.id
}

async function getSubcategoryId(categorySlug: string, subSlug: string): Promise<string> {
  const catId = await getCategoryId(categorySlug)
  const { data, error } = await supabase.from('subcategories').select('id').eq('category_id', catId).eq('slug', subSlug).single()
  if (error) throw new Error(`Subcategory "${categorySlug}/${subSlug}" not found: ${error.message}`)
  return data.id
}

async function getAreaId(slug: string): Promise<string> {
  const { data, error } = await supabase.from('areas').select('id').eq('slug', slug).single()
  if (error) throw new Error(`Area "${slug}" not found: ${error.message}`)
  return data.id
}

async function upsertItems(items: any[]) {
  const { error } = await supabase.from('items').upsert(items, { onConflict: 'subcategory_id,slug' })
  if (error) throw new Error(`Upsert failed: ${error.message}`)
}

// --- Main ---

async function main() {
  console.log('Starting content addition...\n')

  // Fetch all area IDs
  const [costaAdeje, losCristianos, puertoCruz, santaCruz, laLaguna, losGigantes, teide, anaga] = await Promise.all([
    getAreaId('costa-adeje'),
    getAreaId('los-cristianos'),
    getAreaId('puerto-de-la-cruz'),
    getAreaId('santa-cruz'),
    getAreaId('la-laguna'),
    getAreaId('los-gigantes'),
    getAreaId('teide'),
    getAreaId('anaga'),
  ])
  console.log('Areas loaded')

  // Fetch subcategory IDs
  const [
    southBeachesId,
    northBeachesId,
    familyBeachesId,
    teideNPId,
    naturalPoolsId,
    guachinchesId,
    canarianCuisineId,
    wineTastingId,
    waterSportsId,
  ] = await Promise.all([
    getSubcategoryId('beaches', 'south-beaches'),
    getSubcategoryId('beaches', 'north-beaches'),
    getSubcategoryId('beaches', 'family-beaches'),
    getSubcategoryId('nature', 'teide-national-park'),
    getSubcategoryId('nature', 'natural-pools'),
    getSubcategoryId('food', 'guachinches'),
    getSubcategoryId('food', 'canarian-cuisine'),
    getSubcategoryId('food', 'wine-tasting'),
    getSubcategoryId('experiences', 'water-sports'),
  ])
  console.log('Subcategories loaded\n')

  // =============================================
  // SOUTH BEACHES
  // =============================================
  console.log('Adding south beaches...')
  await upsertItems([
    {
      subcategory_id: southBeachesId,
      slug: 'playa-de-fanabe',
      name: { es: 'Playa de Fañabé', en: 'Fañabé Beach', de: 'Strand von Fañabé' },
      description: {
        es: 'Playa de arena dorada de 500 metros en el corazón de Costa Adeje. Muy bien equipada con hamacas, sombrillas, duchas y chiringuitos. Aguas tranquilas protegidas por espigones, ideal para familias. El paseo marítimo conecta con Playa del Duque y Playa de Torviscas.',
        en: 'A 500-meter golden sand beach in the heart of Costa Adeje. Well equipped with sun loungers, parasols, showers and beach bars. Calm waters protected by breakwaters, ideal for families. The promenade connects to Playa del Duque and Playa de Torviscas.',
        de: 'Ein 500 Meter langer Goldstrand im Herzen von Costa Adeje. Gut ausgestattet mit Sonnenliegen, Sonnenschirmen, Duschen und Strandbars. Ruhiges Wasser durch Wellenbrecher geschützt, ideal für Familien. Die Strandpromenade verbindet sich mit Playa del Duque und Playa de Torviscas.',
      },
      short_description: { es: 'Playa dorada bien equipada en Costa Adeje', en: 'Well-equipped golden beach in Costa Adeje', de: 'Gut ausgestatteter Goldstrand in Costa Adeje' },
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      location: { es: 'Costa Adeje', en: 'Costa Adeje' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0825, lng: -16.7350 },
      rating: 4.5,
      review_count: 1120,
      sand_type: { es: 'Arena dorada', en: 'Golden sand', de: 'Goldener Sand' },
      bathing_conditions: { es: 'Aguas tranquilas, protegida por espigones', en: 'Calm waters, protected by breakwaters', de: 'Ruhiges Wasser, durch Wellenbrecher geschützt' },
      accessibility: { es: 'Excelente. Rampas, duchas, aseos, socorristas', en: 'Excellent. Ramps, showers, toilets, lifeguards', de: 'Ausgezeichnet. Rampen, Duschen, Toiletten, Rettungsschwimmer' },
      typical_risk: { es: 'Bajo', en: 'Low', de: 'Niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: southBeachesId,
      slug: 'playa-de-troya',
      name: { es: 'Playa de Troya', en: 'Troya Beach', de: 'Strand von Troya' },
      description: {
        es: 'Playa de arena clara situada entre Playa de las Américas y Costa Adeje. Dividida en Troya I y Troya II, cuenta con todos los servicios: hamacas, chiringuitos, deportes acuáticos y un animado paseo marítimo lleno de restaurantes y tiendas.',
        en: 'A light sand beach located between Playa de las Américas and Costa Adeje. Divided into Troya I and Troya II, it has all the services: sun loungers, beach bars, water sports and a lively promenade full of restaurants and shops.',
        de: 'Ein heller Sandstrand zwischen Playa de las Américas und Costa Adeje. Aufgeteilt in Troya I und Troya II, bietet er alle Annehmlichkeiten: Sonnenliegen, Strandbars, Wassersport und eine lebhafte Promenade voller Restaurants und Geschäfte.',
      },
      short_description: { es: 'Playa animada entre Las Américas y Adeje', en: 'Lively beach between Las Américas and Adeje', de: 'Lebhafter Strand zwischen Las Américas und Adeje' },
      image: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800&q=80',
      location: { es: 'Costa Adeje / Playa de las Américas', en: 'Costa Adeje / Playa de las Américas' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0740, lng: -16.7290 },
      rating: 4.3,
      review_count: 870,
      sand_type: { es: 'Arena clara', en: 'Light sand', de: 'Heller Sand' },
      bathing_conditions: { es: 'Aguas tranquilas, oleaje moderado ocasional', en: 'Calm waters, occasional moderate swell', de: 'Ruhiges Wasser, gelegentlich mäßiger Wellengang' },
      accessibility: { es: 'Muy buena. Todos los servicios disponibles', en: 'Very good. All services available', de: 'Sehr gut. Alle Einrichtungen vorhanden' },
      typical_risk: { es: 'Bajo', en: 'Low', de: 'Niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: southBeachesId,
      slug: 'playa-de-los-cristianos',
      name: { es: 'Playa de Los Cristianos', en: 'Los Cristianos Beach', de: 'Strand von Los Cristianos' },
      description: {
        es: 'Playa urbana en el antiguo pueblo pesquero de Los Cristianos. Arena gris dorada con aguas muy tranquilas gracias al puerto que la protege. Ideal para niños pequeños y personas mayores. Rodeada del encanto del casco antiguo con restaurantes de pescado fresco.',
        en: 'Urban beach in the old fishing village of Los Cristianos. Grey-golden sand with very calm waters thanks to the harbor that protects it. Ideal for small children and elderly visitors. Surrounded by the charm of the old town with fresh fish restaurants.',
        de: 'Stadtstrand im alten Fischerdorf Los Cristianos. Grau-goldener Sand mit sehr ruhigem Wasser dank des schützenden Hafens. Ideal für kleine Kinder und ältere Besucher. Umgeben vom Charme der Altstadt mit Fischrestaurants.',
      },
      short_description: { es: 'Playa tranquila en pueblo pesquero', en: 'Calm beach in fishing village', de: 'Ruhiger Strand im Fischerdorf' },
      image: 'https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?w=800&q=80',
      location: { es: 'Los Cristianos', en: 'Los Cristianos' },
      area_id: losCristianos,
      coordinates: { lat: 28.0498, lng: -16.7150 },
      rating: 4.2,
      review_count: 950,
      sand_type: { es: 'Arena gris dorada', en: 'Grey-golden sand', de: 'Grau-goldener Sand' },
      bathing_conditions: { es: 'Aguas muy tranquilas, protegida por el puerto', en: 'Very calm waters, protected by the harbor', de: 'Sehr ruhiges Wasser, durch den Hafen geschützt' },
      accessibility: { es: 'Excelente. Zona peatonal, rampas, todos los servicios', en: 'Excellent. Pedestrian zone, ramps, all services', de: 'Ausgezeichnet. Fußgängerzone, Rampen, alle Einrichtungen' },
      typical_risk: { es: 'Muy bajo', en: 'Very low', de: 'Sehr niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: southBeachesId,
      slug: 'playa-de-las-americas',
      name: { es: 'Playa de las Américas', en: 'Playa de las Américas', de: 'Playa de las Américas' },
      description: {
        es: 'El epicentro turístico del sur de Tenerife. Varias playas conectadas por un largo paseo marítimo con la mayor concentración de hoteles, discotecas y restaurantes de la isla. Arena oscura volcánica con buenas condiciones para el surf en la zona de La Izquierda.',
        en: 'The tourist epicenter of southern Tenerife. Several beaches connected by a long promenade with the highest concentration of hotels, nightclubs and restaurants on the island. Dark volcanic sand with good surfing conditions at La Izquierda.',
        de: 'Das touristische Epizentrum im Süden Teneriffas. Mehrere Strände, verbunden durch eine lange Promenade mit der höchsten Konzentration an Hotels, Nachtclubs und Restaurants der Insel. Dunkler Vulkansand mit guten Surfbedingungen bei La Izquierda.',
      },
      short_description: { es: 'Epicentro turístico del sur', en: 'Tourist epicenter of the south', de: 'Touristisches Epizentrum des Südens' },
      image: 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800&q=80',
      location: { es: 'Playa de las Américas, Arona', en: 'Playa de las Américas, Arona' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0600, lng: -16.7260 },
      rating: 4.1,
      review_count: 1540,
      sand_type: { es: 'Arena oscura volcánica', en: 'Dark volcanic sand', de: 'Dunkler Vulkansand' },
      bathing_conditions: { es: 'Variable. Algunas zonas protegidas, otras con oleaje para surf', en: 'Variable. Some areas sheltered, others with surf waves', de: 'Variabel. Einige geschützte Bereiche, andere mit Surfwellen' },
      accessibility: { es: 'Muy buena. Paseo marítimo accesible, todos los servicios', en: 'Very good. Accessible promenade, all services', de: 'Sehr gut. Barrierefreie Promenade, alle Einrichtungen' },
      typical_risk: { es: 'Bajo-medio según la zona', en: 'Low-medium depending on area', de: 'Niedrig-mittel je nach Bereich' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 4,
      visible: true,
    },
    {
      subcategory_id: southBeachesId,
      slug: 'playa-de-las-vistas',
      name: { es: 'Playa de las Vistas', en: 'Las Vistas Beach', de: 'Strand Las Vistas' },
      description: {
        es: 'Una de las playas más amplias y populares del sur con casi un kilómetro de arena dorada. Aguas cristalinas y tranquilas, perfecta para familias. Conecta Los Cristianos con Las Américas por un bonito paseo marítimo. Bandera azul consecutiva.',
        en: 'One of the widest and most popular southern beaches with almost a kilometer of golden sand. Crystal clear calm waters, perfect for families. Connects Los Cristianos with Las Américas via a beautiful promenade. Consecutive Blue Flag award.',
        de: 'Einer der breitesten und beliebtesten Südstrände mit fast einem Kilometer goldenem Sand. Kristallklares, ruhiges Wasser, perfekt für Familien. Verbindet Los Cristianos mit Las Américas über eine schöne Promenade. Mehrfach mit Blauer Flagge ausgezeichnet.',
      },
      short_description: { es: 'Amplia playa dorada con Bandera Azul', en: 'Wide golden Blue Flag beach', de: 'Breiter goldener Strand mit Blauer Flagge' },
      image: 'https://images.unsplash.com/photo-1520942702018-0862200e6873?w=800&q=80',
      location: { es: 'Los Cristianos / Las Américas', en: 'Los Cristianos / Las Américas' },
      area_id: losCristianos,
      coordinates: { lat: 28.0530, lng: -16.7200 },
      rating: 4.6,
      review_count: 1380,
      sand_type: { es: 'Arena dorada', en: 'Golden sand', de: 'Goldener Sand' },
      bathing_conditions: { es: 'Aguas tranquilas y cristalinas, espigones de protección', en: 'Calm crystal clear waters, protective breakwaters', de: 'Ruhiges, kristallklares Wasser, Wellenbrecher zum Schutz' },
      accessibility: { es: 'Excelente. Bandera Azul, todos los servicios, acceso adaptado', en: 'Excellent. Blue Flag, all services, adapted access', de: 'Ausgezeichnet. Blaue Flagge, alle Einrichtungen, barrierefreier Zugang' },
      typical_risk: { es: 'Bajo', en: 'Low', de: 'Niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 5,
      visible: true,
    },
  ])
  console.log('South beaches added')

  // =============================================
  // NORTH BEACHES
  // =============================================
  console.log('Adding north beaches...')
  await upsertItems([
    {
      subcategory_id: northBeachesId,
      slug: 'playa-del-bollullo',
      name: { es: 'Playa del Bollullo', en: 'Bollullo Beach', de: 'Strand von Bollullo' },
      description: {
        es: 'Playa virgen de arena negra volcánica escondida tras los plataneras del Valle de la Orotava. Se accede por un sendero empinado de unos 15 minutos desde el aparcamiento. Sin servicios pero con un chiringuito rústico. Oleaje fuerte, no apta para nadadores inexpertos. Una de las playas más bonitas de Tenerife.',
        en: 'A pristine black volcanic sand beach hidden behind the banana plantations of the Orotava Valley. Accessed via a steep 15-minute path from the parking area. No services but a rustic beach bar. Strong waves, not suitable for inexperienced swimmers. One of the most beautiful beaches in Tenerife.',
        de: 'Ein unberührter schwarzer Vulkansandstrand, versteckt hinter den Bananenplantagen des Orotava-Tals. Zugang über einen steilen 15-minütigen Pfad vom Parkplatz. Keine Einrichtungen, aber eine rustikale Strandbar. Starke Wellen, nicht für unerfahrene Schwimmer geeignet. Einer der schönsten Strände Teneriffas.',
      },
      short_description: { es: 'Playa virgen de arena negra en el norte', en: 'Pristine black sand beach in the north', de: 'Unberührter schwarzer Sandstrand im Norden' },
      image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
      location: { es: 'La Orotava, Puerto de la Cruz', en: 'La Orotava, Puerto de la Cruz' },
      area_id: puertoCruz,
      coordinates: { lat: 28.4020, lng: -16.5050 },
      rating: 4.7,
      review_count: 680,
      sand_type: { es: 'Arena negra volcánica', en: 'Black volcanic sand', de: 'Schwarzer Vulkansand' },
      bathing_conditions: { es: 'Oleaje fuerte, corrientes. Precaución', en: 'Strong waves, currents. Caution required', de: 'Starke Wellen, Strömungen. Vorsicht geboten' },
      accessibility: { es: 'Difícil. Sendero empinado, sin servicios', en: 'Difficult. Steep path, no facilities', de: 'Schwierig. Steiler Pfad, keine Einrichtungen' },
      typical_risk: { es: 'Alto. Oleaje fuerte y corrientes', en: 'High. Strong waves and currents', de: 'Hoch. Starke Wellen und Strömungen' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: northBeachesId,
      slug: 'playa-de-los-patos',
      name: { es: 'Playa de los Patos', en: 'Los Patos Beach', de: 'Strand Los Patos' },
      description: {
        es: 'Playa salvaje de arena negra al lado de Bollullo, aún más aislada y menos frecuentada. Rodeada de imponentes acantilados y vegetación subtropical. El acceso requiere caminar unos 25 minutos por sendero. Sin servicios ni vigilancia. Un paraíso para amantes de la naturaleza que buscan soledad.',
        en: 'Wild black sand beach next to Bollullo, even more isolated and less frequented. Surrounded by imposing cliffs and subtropical vegetation. Access requires a 25-minute walk along a trail. No services or surveillance. A paradise for nature lovers seeking solitude.',
        de: 'Wilder schwarzer Sandstrand neben Bollullo, noch isolierter und weniger besucht. Umgeben von imposanten Klippen und subtropischer Vegetation. Zugang erfordert einen 25-minütigen Fußmarsch. Keine Einrichtungen oder Überwachung. Ein Paradies für Naturliebhaber, die Einsamkeit suchen.',
      },
      short_description: { es: 'Playa salvaje aislada junto a Bollullo', en: 'Isolated wild beach next to Bollullo', de: 'Isolierter wilder Strand neben Bollullo' },
      image: 'https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800&q=80',
      location: { es: 'La Orotava', en: 'La Orotava' },
      area_id: puertoCruz,
      coordinates: { lat: 28.4035, lng: -16.5020 },
      rating: 4.6,
      review_count: 320,
      sand_type: { es: 'Arena negra volcánica', en: 'Black volcanic sand', de: 'Schwarzer Vulkansand' },
      bathing_conditions: { es: 'Peligroso. Oleaje muy fuerte, sin vigilancia', en: 'Dangerous. Very strong waves, no lifeguard', de: 'Gefährlich. Sehr starke Wellen, keine Rettungsschwimmer' },
      accessibility: { es: 'Muy difícil. Sendero largo y empinado', en: 'Very difficult. Long and steep trail', de: 'Sehr schwierig. Langer und steiler Weg' },
      typical_risk: { es: 'Muy alto', en: 'Very high', de: 'Sehr hoch' },
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: northBeachesId,
      slug: 'playa-del-socorro',
      name: { es: 'Playa del Socorro', en: 'El Socorro Beach', de: 'Strand El Socorro' },
      description: {
        es: 'Playa de arena negra muy popular entre surfistas y bodyboarders por su oleaje consistente. Situada en Los Realejos con fácil acceso en coche y aparcamiento. Cuenta con duchas, socorristas en temporada y un entorno espectacular con acantilados. Peligrosa para el baño por las corrientes.',
        en: 'A black sand beach very popular among surfers and bodyboarders for its consistent waves. Located in Los Realejos with easy car access and parking. Has showers, lifeguards in season and a spectacular setting with cliffs. Dangerous for swimming due to currents.',
        de: 'Ein schwarzer Sandstrand, der bei Surfern und Bodyboardern wegen seiner konstanten Wellen sehr beliebt ist. In Los Realejos gelegen, mit einfacher Anfahrt und Parkplatz. Duschen, Rettungsschwimmer in der Saison und eine spektakuläre Kulisse mit Klippen. Wegen Strömungen gefährlich zum Schwimmen.',
      },
      short_description: { es: 'Playa de surf con oleaje consistente', en: 'Surf beach with consistent waves', de: 'Surfstrand mit konstanten Wellen' },
      image: 'https://images.unsplash.com/photo-1502680390548-bdbac40e4a9f?w=800&q=80',
      location: { es: 'Los Realejos', en: 'Los Realejos' },
      area_id: puertoCruz,
      coordinates: { lat: 28.3870, lng: -16.5150 },
      rating: 4.4,
      review_count: 510,
      sand_type: { es: 'Arena negra volcánica', en: 'Black volcanic sand', de: 'Schwarzer Vulkansand' },
      bathing_conditions: { es: 'Oleaje fuerte, ideal para surf. Corrientes peligrosas', en: 'Strong waves, ideal for surfing. Dangerous currents', de: 'Starke Wellen, ideal zum Surfen. Gefährliche Strömungen' },
      accessibility: { es: 'Buena. Aparcamiento, duchas, socorristas en verano', en: 'Good. Parking, showers, lifeguards in summer', de: 'Gut. Parkplatz, Duschen, Rettungsschwimmer im Sommer' },
      typical_risk: { es: 'Alto para baño, medio para surf', en: 'High for swimming, medium for surfing', de: 'Hoch zum Schwimmen, mittel zum Surfen' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: northBeachesId,
      slug: 'playa-jardin',
      name: { es: 'Playa Jardín', en: 'Playa Jardín', de: 'Playa Jardín' },
      description: {
        es: 'Playa de arena negra diseñada por el artista lanzaroteño César Manrique, integrada en un precioso jardín tropical con palmeras, cascadas y plantas exóticas. Situada en Puerto de la Cruz, es la playa más bonita del norte urbano. Bien equipada con restaurantes, duchas y socorristas.',
        en: 'A black sand beach designed by Lanzarote artist César Manrique, set within beautiful tropical gardens with palm trees, waterfalls and exotic plants. Located in Puerto de la Cruz, it is the most beautiful beach in the urban north. Well equipped with restaurants, showers and lifeguards.',
        de: 'Ein schwarzer Sandstrand, gestaltet vom Lanzarote-Künstler César Manrique, eingebettet in wunderschöne tropische Gärten mit Palmen, Wasserfällen und exotischen Pflanzen. In Puerto de la Cruz gelegen, ist er der schönste Strand im urbanen Norden. Gut ausgestattet mit Restaurants, Duschen und Rettungsschwimmern.',
      },
      short_description: { es: 'Playa negra diseñada por César Manrique', en: 'Black beach designed by César Manrique', de: 'Schwarzer Strand von César Manrique gestaltet' },
      image: 'https://images.unsplash.com/photo-1476673160081-cf065607f449?w=800&q=80',
      location: { es: 'Puerto de la Cruz', en: 'Puerto de la Cruz' },
      area_id: puertoCruz,
      coordinates: { lat: 28.4170, lng: -16.5520 },
      rating: 4.5,
      review_count: 920,
      sand_type: { es: 'Arena negra volcánica', en: 'Black volcanic sand', de: 'Schwarzer Vulkansand' },
      bathing_conditions: { es: 'Oleaje moderado, espigones de protección parcial', en: 'Moderate waves, partial breakwater protection', de: 'Mäßige Wellen, teilweiser Wellenbrecherschutz' },
      accessibility: { es: 'Muy buena. Accesible, todos los servicios, aparcamiento', en: 'Very good. Accessible, all services, parking', de: 'Sehr gut. Barrierefrei, alle Einrichtungen, Parkplatz' },
      typical_risk: { es: 'Medio. Oleaje ocasional', en: 'Medium. Occasional swell', de: 'Mittel. Gelegentlicher Wellengang' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 4,
      visible: true,
    },
    {
      subcategory_id: northBeachesId,
      slug: 'playa-de-la-arena',
      name: { es: 'Playa de la Arena', en: 'La Arena Beach', de: 'Strand La Arena' },
      description: {
        es: 'Playa de arena negra volcánica en Santiago del Teide con vistas a los acantilados de Los Gigantes. Bandera Azul por su calidad de aguas y servicios. Arena muy fina que se calienta con el sol. Cuenta con paseo marítimo, restaurantes y buena infraestructura. Oleaje moderado con socorristas.',
        en: 'A black volcanic sand beach in Santiago del Teide with views of the Los Gigantes cliffs. Blue Flag for its water quality and services. Very fine sand that warms in the sun. Features a promenade, restaurants and good infrastructure. Moderate waves with lifeguards.',
        de: 'Ein schwarzer Vulkansandstrand in Santiago del Teide mit Blick auf die Klippen von Los Gigantes. Blaue Flagge für Wasserqualität und Einrichtungen. Sehr feiner Sand, der sich in der Sonne erwärmt. Promenade, Restaurants und gute Infrastruktur. Mäßige Wellen mit Rettungsschwimmern.',
      },
      short_description: { es: 'Arena negra con vistas a Los Gigantes', en: 'Black sand with Los Gigantes views', de: 'Schwarzer Sand mit Blick auf Los Gigantes' },
      image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
      location: { es: 'Santiago del Teide', en: 'Santiago del Teide' },
      area_id: losGigantes,
      coordinates: { lat: 28.2370, lng: -16.8430 },
      rating: 4.4,
      review_count: 760,
      sand_type: { es: 'Arena negra volcánica muy fina', en: 'Very fine black volcanic sand', de: 'Sehr feiner schwarzer Vulkansand' },
      bathing_conditions: { es: 'Oleaje moderado, socorristas en temporada', en: 'Moderate waves, lifeguards in season', de: 'Mäßige Wellen, Rettungsschwimmer in der Saison' },
      accessibility: { es: 'Buena. Bandera Azul, aparcamiento, todos los servicios', en: 'Good. Blue Flag, parking, all services', de: 'Gut. Blaue Flagge, Parkplatz, alle Einrichtungen' },
      typical_risk: { es: 'Medio', en: 'Medium', de: 'Mittel' },
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 5,
      visible: true,
    },
  ])
  console.log('North beaches added')

  // =============================================
  // FAMILY BEACHES
  // =============================================
  console.log('Adding family beaches...')
  await upsertItems([
    {
      subcategory_id: familyBeachesId,
      slug: 'playa-de-las-vistas-family',
      name: { es: 'Playa de las Vistas', en: 'Las Vistas Beach', de: 'Strand Las Vistas' },
      description: {
        es: 'La playa favorita de las familias en el sur. Arena dorada fina, aguas cristalinas y calmadas gracias a los espigones. Socorristas todo el año, zona de juegos infantiles, restaurantes cercanos y fácil acceso con cochecitos. Bandera Azul por su excelente calidad.',
        en: 'The favorite family beach in the south. Fine golden sand, crystal clear calm waters thanks to breakwaters. Year-round lifeguards, children\'s play area, nearby restaurants and easy stroller access. Blue Flag for excellent quality.',
        de: 'Der Lieblingsfamilienstrand im Süden. Feiner goldener Sand, kristallklares ruhiges Wasser dank Wellenbrecher. Ganzjährige Rettungsschwimmer, Kinderspielplatz, nahegelegene Restaurants und einfacher Zugang mit Kinderwagen. Blaue Flagge für ausgezeichnete Qualität.',
      },
      short_description: { es: 'La mejor playa familiar del sur', en: 'Best family beach in the south', de: 'Bester Familienstrand im Süden' },
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
      location: { es: 'Los Cristianos', en: 'Los Cristianos' },
      area_id: losCristianos,
      coordinates: { lat: 28.0530, lng: -16.7200 },
      rating: 4.6,
      review_count: 1250,
      sand_type: { es: 'Arena dorada fina', en: 'Fine golden sand', de: 'Feiner goldener Sand' },
      bathing_conditions: { es: 'Aguas muy tranquilas, ideal para niños', en: 'Very calm waters, ideal for children', de: 'Sehr ruhiges Wasser, ideal für Kinder' },
      accessibility: { es: 'Excelente. Acceso adaptado, zona infantil, socorristas', en: 'Excellent. Adapted access, children\'s area, lifeguards', de: 'Ausgezeichnet. Barrierefreier Zugang, Kinderbereich, Rettungsschwimmer' },
      typical_risk: { es: 'Muy bajo', en: 'Very low', de: 'Sehr niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: familyBeachesId,
      slug: 'playa-del-duque-family',
      name: { es: 'Playa del Duque', en: 'Duque Beach', de: 'Strand El Duque' },
      description: {
        es: 'Playa premium ideal para familias que buscan comodidad y seguridad. Arena dorada, aguas cristalinas sin oleaje, hamacas de primera calidad y restaurantes elegantes alrededor. Los niños pueden jugar tranquilamente mientras los padres disfrutan del ambiente exclusivo de Costa Adeje.',
        en: 'Premium beach ideal for families seeking comfort and safety. Golden sand, crystal clear waters with no waves, high-quality sun loungers and elegant restaurants around. Children can play safely while parents enjoy the exclusive atmosphere of Costa Adeje.',
        de: 'Premium-Strand ideal für Familien, die Komfort und Sicherheit suchen. Goldener Sand, kristallklares Wasser ohne Wellen, hochwertige Sonnenliegen und elegante Restaurants. Kinder können sicher spielen, während Eltern die exklusive Atmosphäre von Costa Adeje genießen.',
      },
      short_description: { es: 'Playa premium segura para familias', en: 'Premium safe beach for families', de: 'Premium-sicherer Strand für Familien' },
      image: 'https://images.unsplash.com/photo-1559511260-66a654ae982a?w=800&q=80',
      location: { es: 'Costa Adeje', en: 'Costa Adeje' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0890, lng: -16.7410 },
      rating: 4.7,
      review_count: 890,
      sand_type: { es: 'Arena dorada', en: 'Golden sand', de: 'Goldener Sand' },
      bathing_conditions: { es: 'Aguas tranquilas, perfectas para niños', en: 'Calm waters, perfect for children', de: 'Ruhiges Wasser, perfekt für Kinder' },
      accessibility: { es: 'Excelente. Rampas, todos los servicios, socorristas', en: 'Excellent. Ramps, all services, lifeguards', de: 'Ausgezeichnet. Rampen, alle Einrichtungen, Rettungsschwimmer' },
      typical_risk: { es: 'Bajo', en: 'Low', de: 'Niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: familyBeachesId,
      slug: 'playa-de-las-teresitas-family',
      name: { es: 'Playa de las Teresitas', en: 'Las Teresitas Beach', de: 'Strand Las Teresitas' },
      description: {
        es: 'La playa más icónica de Tenerife es también perfecta para familias. Su arena dorada importada y las aguas calmadas por el rompeolas artificial la hacen segura para niños. Aparcamiento gratuito, merenderos con sombra y el pueblo de San Andrés con restaurantes de pescado fresco a 2 minutos.',
        en: 'Tenerife\'s most iconic beach is also perfect for families. Its imported golden sand and waters calmed by the artificial breakwater make it safe for children. Free parking, shaded picnic areas and the village of San Andrés with fresh fish restaurants 2 minutes away.',
        de: 'Teneriffas berühmtester Strand ist auch perfekt für Familien. Der importierte goldene Sand und das durch den künstlichen Wellenbrecher beruhigte Wasser machen ihn sicher für Kinder. Kostenloser Parkplatz, schattige Picknickplätze und das Dorf San Andrés mit Fischrestaurants 2 Minuten entfernt.',
      },
      short_description: { es: 'Playa icónica segura para toda la familia', en: 'Iconic beach safe for all the family', de: 'Ikonischer Strand, sicher für die ganze Familie' },
      image: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80',
      location: { es: 'San Andrés, Santa Cruz', en: 'San Andrés, Santa Cruz' },
      area_id: santaCruz,
      coordinates: { lat: 28.5080, lng: -16.1870 },
      rating: 4.5,
      review_count: 1100,
      sand_type: { es: 'Arena dorada importada', en: 'Imported golden sand', de: 'Importierter goldener Sand' },
      bathing_conditions: { es: 'Aguas muy tranquilas, rompeolas de protección', en: 'Very calm waters, protective breakwater', de: 'Sehr ruhiges Wasser, Wellenbrecher zum Schutz' },
      accessibility: { es: 'Buena. Aparcamiento amplio y gratuito, duchas', en: 'Good. Large free parking, showers', de: 'Gut. Großer kostenloser Parkplatz, Duschen' },
      typical_risk: { es: 'Muy bajo', en: 'Very low', de: 'Sehr niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: familyBeachesId,
      slug: 'playa-de-fanabe-family',
      name: { es: 'Playa de Fañabé', en: 'Fañabé Beach', de: 'Strand Fañabé' },
      description: {
        es: 'Playa amplia y cómoda en Costa Adeje con todos los servicios que una familia necesita: socorristas, hamacas, sombrillas, duchas, aseos y chiringuitos. Arena dorada con aguas protegidas por espigones. Los niños pueden disfrutar de actividades acuáticas como banana boat y pedales.',
        en: 'A spacious and comfortable beach in Costa Adeje with all the services a family needs: lifeguards, sun loungers, parasols, showers, toilets and beach bars. Golden sand with waters protected by breakwaters. Children can enjoy water activities like banana boat and pedal boats.',
        de: 'Ein geräumiger und komfortabler Strand in Costa Adeje mit allen Einrichtungen, die eine Familie braucht: Rettungsschwimmer, Sonnenliegen, Sonnenschirme, Duschen, Toiletten und Strandbars. Goldener Sand mit durch Wellenbrecher geschütztem Wasser. Kinder können Wasseraktivitäten wie Bananenboot und Tretboot genießen.',
      },
      short_description: { es: 'Playa familiar con todos los servicios', en: 'Family beach with all services', de: 'Familienstrand mit allen Einrichtungen' },
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      location: { es: 'Costa Adeje', en: 'Costa Adeje' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0825, lng: -16.7350 },
      rating: 4.4,
      review_count: 780,
      sand_type: { es: 'Arena dorada', en: 'Golden sand', de: 'Goldener Sand' },
      bathing_conditions: { es: 'Aguas tranquilas, espigones protectores', en: 'Calm waters, protective breakwaters', de: 'Ruhiges Wasser, Wellenbrecher' },
      accessibility: { es: 'Excelente. Rampas, duchas, aseos, socorristas', en: 'Excellent. Ramps, showers, toilets, lifeguards', de: 'Ausgezeichnet. Rampen, Duschen, Toiletten, Rettungsschwimmer' },
      typical_risk: { es: 'Bajo', en: 'Low', de: 'Niedrig' },
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 4,
      visible: true,
    },
  ])
  console.log('Family beaches added')

  // =============================================
  // TEIDE NATIONAL PARK
  // =============================================
  console.log('Adding Teide National Park items...')
  await upsertItems([
    {
      subcategory_id: teideNPId,
      slug: 'teleferico-del-teide',
      name: { es: 'Teleférico del Teide', en: 'Teide Cable Car', de: 'Teide Seilbahn' },
      description: {
        es: 'El teleférico sube desde la base a 2.356m hasta La Rambleta a 3.555m en solo 8 minutos, ofreciendo vistas espectaculares de las islas vecinas y el mar de nubes. Desde arriba, puedes recorrer senderos con vistas al cráter o subir al pico (3.718m) con permiso previo gratuito. Imprescindible reservar con antelación en temporada alta.',
        en: 'The cable car ascends from the base at 2,356m to La Rambleta at 3,555m in just 8 minutes, offering spectacular views of neighboring islands and the sea of clouds. From the top, you can walk trails with crater views or summit the peak (3,718m) with a free advance permit. Essential to book ahead in high season.',
        de: 'Die Seilbahn fährt von der Basis auf 2.356m zur La Rambleta auf 3.555m in nur 8 Minuten und bietet spektakuläre Ausblicke auf die Nachbarinseln und das Wolkenmeer. Von oben können Sie Wanderwege mit Kraterblick gehen oder den Gipfel (3.718m) mit kostenloser Voranmeldung besteigen. In der Hochsaison unbedingt vorher buchen.',
      },
      short_description: { es: 'Sube a 3.555m en 8 minutos', en: 'Ascend to 3,555m in 8 minutes', de: 'Aufstieg auf 3.555m in 8 Minuten' },
      image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
      location: { es: 'Parque Nacional del Teide', en: 'Teide National Park' },
      area_id: teide,
      coordinates: { lat: 28.2566, lng: -16.6291 },
      rating: 4.7,
      review_count: 3200,
      price_from: 39,
      currency: 'EUR',
      duration: '1-3 hours',
      bookable: true,
      booking_url: 'https://www.volcanoteide.com',
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: teideNPId,
      slug: 'paisaje-lunar',
      name: { es: 'Sendero del Paisaje Lunar', en: 'Lunar Landscape Trail', de: 'Mondlandschaft Wanderweg' },
      description: {
        es: 'Ruta de senderismo circular de unos 6 km que lleva a formaciones rocosas erosionadas que parecen sacadas de otro planeta. Las chimeneas de hada de piedra pómez blanca contrastan con el pinar canario. Se inicia desde el aparcamiento de la Degollada de las Yeguas. Dificultad media, llevar agua y protección solar.',
        en: 'A circular hiking trail of about 6 km leading to eroded rock formations that look like they are from another planet. The white pumice fairy chimneys contrast with the Canarian pine forest. Starting from the Degollada de las Yeguas car park. Medium difficulty, bring water and sun protection.',
        de: 'Ein Rundwanderweg von ca. 6 km zu erodierten Felsformationen, die wie von einem anderen Planeten aussehen. Die weißen Bimsstein-Feenkamine kontrastieren mit dem kanarischen Kiefernwald. Start am Parkplatz Degollada de las Yeguas. Mittlerer Schwierigkeitsgrad, Wasser und Sonnenschutz mitbringen.',
      },
      short_description: { es: 'Formaciones rocosas de otro planeta', en: 'Rock formations from another planet', de: 'Felsformationen wie von einem anderen Planeten' },
      image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80',
      location: { es: 'Vilaflor, Parque Nacional del Teide', en: 'Vilaflor, Teide National Park' },
      area_id: teide,
      coordinates: { lat: 28.1830, lng: -16.6310 },
      rating: 4.6,
      review_count: 540,
      price_from: 0,
      duration: '3-4 hours',
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: teideNPId,
      slug: 'roques-de-garcia',
      name: { es: 'Roques de García', en: 'Roques de García', de: 'Roques de García' },
      description: {
        es: 'Formaciones rocosas emblemáticas del Parque Nacional, incluido el famoso Roque Cinchado (que aparecía en los billetes de 1.000 pesetas). El sendero circular de 3,5 km rodea estas impresionantes agujas volcánicas con vistas al Teide y a la caldera de Las Cañadas. Fácil acceso desde el Parador Nacional.',
        en: 'Iconic rock formations of the National Park, including the famous Roque Cinchado (which appeared on the 1,000 peseta banknote). The 3.5 km circular trail surrounds these impressive volcanic pinnacles with views of Teide and the Las Cañadas caldera. Easy access from the Parador Nacional.',
        de: 'Ikonische Felsformationen des Nationalparks, darunter der berühmte Roque Cinchado (der auf dem 1.000-Peseten-Schein abgebildet war). Der 3,5 km lange Rundweg umgibt diese beeindruckenden vulkanischen Nadeln mit Blick auf den Teide und die Las-Cañadas-Caldera. Einfacher Zugang vom Parador Nacional.',
      },
      short_description: { es: 'Formaciones volcánicas icónicas', en: 'Iconic volcanic formations', de: 'Ikonische vulkanische Formationen' },
      image: 'https://images.unsplash.com/photo-1547234935-80c7145ec969?w=800&q=80',
      location: { es: 'Parque Nacional del Teide', en: 'Teide National Park' },
      area_id: teide,
      coordinates: { lat: 28.2240, lng: -16.6330 },
      rating: 4.8,
      review_count: 1890,
      price_from: 0,
      duration: '1.5-2 hours',
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: teideNPId,
      slug: 'pico-viejo',
      name: { es: 'Sendero de Pico Viejo', en: 'Pico Viejo Trail', de: 'Pico Viejo Wanderweg' },
      description: {
        es: 'Ruta desde la estación superior del teleférico hasta el mirador de Pico Viejo (3.135m), el segundo volcán más alto de Canarias. Ofrece unas vistas impresionantes del enorme cráter de 800 metros de diámetro y de la isla de La Gomera. Sendero de dificultad media-baja, no requiere permiso.',
        en: 'Trail from the upper cable car station to the Pico Viejo viewpoint (3,135m), the second highest volcano in the Canaries. Offers impressive views of the enormous 800-meter diameter crater and La Gomera island. Medium-low difficulty trail, no permit required.',
        de: 'Wanderweg von der oberen Seilbahnstation zum Aussichtspunkt Pico Viejo (3.135m), dem zweithöchsten Vulkan der Kanaren. Bietet beeindruckende Ausblicke auf den enormen Krater von 800 Metern Durchmesser und die Insel La Gomera. Mittlerer bis niedriger Schwierigkeitsgrad, keine Genehmigung erforderlich.',
      },
      short_description: { es: 'Segundo volcán más alto de Canarias', en: 'Second highest volcano in the Canaries', de: 'Zweithöchster Vulkan der Kanaren' },
      image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80',
      location: { es: 'Parque Nacional del Teide', en: 'Teide National Park' },
      area_id: teide,
      coordinates: { lat: 28.2560, lng: -16.6460 },
      rating: 4.7,
      review_count: 420,
      price_from: 39,
      currency: 'EUR',
      duration: '2-3 hours',
      bookable: true,
      featured: false,
      sort_order: 4,
      visible: true,
    },
  ])
  console.log('Teide National Park items added')

  // =============================================
  // NATURAL POOLS
  // =============================================
  console.log('Adding natural pools...')
  await upsertItems([
    {
      subcategory_id: naturalPoolsId,
      slug: 'charco-de-la-laja',
      name: { es: 'Charco de la Laja', en: 'Charco de la Laja', de: 'Charco de la Laja' },
      description: {
        es: 'Piscina natural formada por rocas volcánicas en San Juan de la Rambla, al norte de Tenerife. Aguas cristalinas y tranquilas protegidas del oleaje del Atlántico. Un lugar muy frecuentado por locales que conserva su autenticidad. Cuenta con escaleras de acceso y un pequeño aparcamiento. Ideal al atardecer.',
        en: 'Natural pool formed by volcanic rocks in San Juan de la Rambla, in northern Tenerife. Crystal clear calm waters protected from Atlantic waves. A spot very popular with locals that retains its authenticity. Has access stairs and a small car park. Ideal at sunset.',
        de: 'Natürlicher Pool aus Vulkangestein in San Juan de la Rambla im Norden Teneriffas. Kristallklares, ruhiges Wasser, geschützt vor den Atlantikwellen. Ein bei Einheimischen beliebter Ort, der seine Authentizität bewahrt hat. Mit Zugangstreppen und kleinem Parkplatz. Ideal bei Sonnenuntergang.',
      },
      short_description: { es: 'Piscina natural volcánica en el norte', en: 'Volcanic natural pool in the north', de: 'Vulkanischer Naturpool im Norden' },
      image: 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&q=80',
      location: { es: 'San Juan de la Rambla', en: 'San Juan de la Rambla' },
      area_id: null,
      coordinates: { lat: 28.3950, lng: -16.6220 },
      rating: 4.5,
      review_count: 340,
      price_from: 0,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: naturalPoolsId,
      slug: 'charco-del-viento',
      name: { es: 'Charco del Viento', en: 'Charco del Viento', de: 'Charco del Viento' },
      description: {
        es: 'Conjunto de piscinas naturales en La Guancha, formadas por coladas de lava que crean pozas de diferentes tamaños y profundidades. Agua de mar renovada con cada marea. Poco conocido por turistas, es un secreto local. Acceso algo complicado por sendero, no apto para personas con movilidad reducida.',
        en: 'A set of natural pools in La Guancha, formed by lava flows creating pools of different sizes and depths. Seawater renewed with each tide. Little known by tourists, it is a local secret. Somewhat difficult trail access, not suitable for people with reduced mobility.',
        de: 'Eine Gruppe natürlicher Pools in La Guancha, geformt durch Lavaströme, die Becken verschiedener Größen und Tiefen bilden. Meerwasser wird mit jeder Flut erneuert. Bei Touristen kaum bekannt, ein Geheimtipp der Einheimischen. Etwas schwieriger Zugang über Pfad, nicht für Personen mit eingeschränkter Mobilität geeignet.',
      },
      short_description: { es: 'Piscinas naturales secretas en La Guancha', en: 'Secret natural pools in La Guancha', de: 'Geheime Naturpools in La Guancha' },
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
      location: { es: 'La Guancha', en: 'La Guancha' },
      area_id: null,
      coordinates: { lat: 28.3890, lng: -16.6540 },
      rating: 4.4,
      review_count: 210,
      price_from: 0,
      currency: 'EUR',
      bookable: false,
      featured: false,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: naturalPoolsId,
      slug: 'piscinas-de-bajamar',
      name: { es: 'Piscinas Naturales de Bajamar', en: 'Bajamar Natural Pools', de: 'Natürliche Schwimmbecken von Bajamar' },
      description: {
        es: 'Complejo de piscinas naturales y semi-artificiales en Bajamar, al norte de La Laguna. Varias pozas de diferentes tamaños con agua de mar renovada constantemente por las olas. Las más grandes tienen escaleras y vestuarios. Ambiente local auténtico, muy concurrido los fines de semana. Las olas pueden salpicar espectacularmente sobre las rocas.',
        en: 'A complex of natural and semi-artificial pools in Bajamar, north of La Laguna. Several pools of different sizes with seawater constantly renewed by the waves. The larger ones have stairs and changing rooms. Authentic local atmosphere, very busy on weekends. Waves can splash spectacularly over the rocks.',
        de: 'Ein Komplex aus natürlichen und halbkünstlichen Becken in Bajamar, nördlich von La Laguna. Mehrere Becken verschiedener Größen mit Meerwasser, das ständig durch die Wellen erneuert wird. Die größeren haben Treppen und Umkleideräume. Authentische lokale Atmosphäre, sehr belebt an Wochenenden. Die Wellen können spektakulär über die Felsen spritzen.',
      },
      short_description: { es: 'Complejo de piscinas naturales en la costa norte', en: 'Natural pool complex on the north coast', de: 'Naturpool-Komplex an der Nordküste' },
      image: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&q=80',
      location: { es: 'Bajamar, San Cristóbal de La Laguna', en: 'Bajamar, La Laguna' },
      area_id: laLaguna,
      coordinates: { lat: 28.5410, lng: -16.3480 },
      rating: 4.3,
      review_count: 560,
      price_from: 0,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: naturalPoolsId,
      slug: 'piscinas-naturales-garachico',
      name: { es: 'Piscinas Naturales de Garachico (El Caletón)', en: 'Garachico Natural Pools (El Caletón)', de: 'Natürliche Schwimmbecken von Garachico (El Caletón)' },
      description: {
        es: 'Las piscinas naturales más famosas de Tenerife, formadas por la erupción del volcán Trevejo en 1706 que destruyó el antiguo puerto. Las coladas de lava crearon pozas perfectas para el baño con agua cristalina. Bien acondicionadas con duchas, vestuarios y acceso adaptado. Imprescindible visitar el pueblo histórico de Garachico.',
        en: 'The most famous natural pools in Tenerife, formed by the eruption of the Trevejo volcano in 1706 which destroyed the old port. The lava flows created perfect bathing pools with crystal clear water. Well equipped with showers, changing rooms and adapted access. A must-visit along with the historic town of Garachico.',
        de: 'Die berühmtesten Naturpools Teneriffas, entstanden durch den Ausbruch des Vulkans Trevejo 1706, der den alten Hafen zerstörte. Die Lavaströme schufen perfekte Badebecken mit kristallklarem Wasser. Gut ausgestattet mit Duschen, Umkleideräumen und barrierefreiem Zugang. Ein Muss zusammen mit der historischen Stadt Garachico.',
      },
      short_description: { es: 'Las piscinas naturales más famosas de la isla', en: 'The most famous natural pools on the island', de: 'Die berühmtesten Naturpools der Insel' },
      image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
      location: { es: 'Garachico', en: 'Garachico' },
      area_id: null,
      coordinates: { lat: 28.3720, lng: -16.7640 },
      rating: 4.7,
      review_count: 1450,
      price_from: 0,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 4,
      visible: true,
    },
  ])
  console.log('Natural pools added')

  // =============================================
  // GUACHINCHES
  // =============================================
  console.log('Adding guachinches...')
  await upsertItems([
    {
      subcategory_id: guachinchesId,
      slug: 'guachinche-el-cubano',
      name: { es: 'Guachinche El Cubano', en: 'Guachinche El Cubano', de: 'Guachinche El Cubano' },
      description: {
        es: 'Uno de los guachinches más auténticos de la zona de La Orotava. Cocina casera canaria con carne de cerdo a la brasa, papas arrugadas con mojo y vino de cosecha propia. Sin lujos ni pretensiones, solo comida honesta a precios populares. Abren solo cuando tienen vino, así que conviene llamar antes.',
        en: 'One of the most authentic guachinches in the La Orotava area. Homemade Canarian cuisine with grilled pork, wrinkled potatoes with mojo and their own harvest wine. No frills or pretensions, just honest food at popular prices. Only open when they have wine, so call ahead.',
        de: 'Eines der authentischsten Guachinches im Gebiet von La Orotava. Hausgemachte kanarische Küche mit gegrilltem Schweinefleisch, Runzelkartoffeln mit Mojo und eigenem Wein. Ohne Schnickschnack, nur ehrliches Essen zu günstigen Preisen. Nur geöffnet wenn Wein da ist, also vorher anrufen.',
      },
      short_description: { es: 'Guachinche auténtico con vino propio', en: 'Authentic guachinche with own wine', de: 'Authentisches Guachinche mit eigenem Wein' },
      image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80',
      location: { es: 'La Orotava', en: 'La Orotava' },
      area_id: puertoCruz,
      coordinates: { lat: 28.3920, lng: -16.5230 },
      rating: 4.6,
      review_count: 280,
      price_from: 8,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: guachinchesId,
      slug: 'guachinche-la-casona',
      name: { es: 'Guachinche La Casona', en: 'Guachinche La Casona', de: 'Guachinche La Casona' },
      description: {
        es: 'Guachinche familiar en la zona de El Sauzal con terraza y vistas al Teide. Especialidad en conejo en salmorejo, carne fiesta y costillas a la brasa. El vino tinto de la casa es suave y afrutado. Raciones generosas a precios imbatibles. Ambiente rústico y acogedor con mesas de madera.',
        en: 'Family guachinche in the El Sauzal area with terrace and Teide views. Specialties include rabbit in salmorejo, carne fiesta and grilled ribs. The house red wine is smooth and fruity. Generous portions at unbeatable prices. Rustic and cozy atmosphere with wooden tables.',
        de: 'Familien-Guachinche im Gebiet El Sauzal mit Terrasse und Teide-Blick. Spezialitäten sind Kaninchen in Salmorejo, Carne Fiesta und gegrillte Rippchen. Der Hauswein ist weich und fruchtig. Großzügige Portionen zu unschlagbaren Preisen. Rustikale und gemütliche Atmosphäre mit Holztischen.',
      },
      short_description: { es: 'Guachinche con terraza y vistas al Teide', en: 'Guachinche with terrace and Teide views', de: 'Guachinche mit Terrasse und Teide-Blick' },
      image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
      location: { es: 'El Sauzal', en: 'El Sauzal' },
      area_id: null,
      coordinates: { lat: 28.4740, lng: -16.4330 },
      rating: 4.5,
      review_count: 350,
      price_from: 7,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: guachinchesId,
      slug: 'guachinche-el-relajo',
      name: { es: 'Guachinche El Relajo', en: 'Guachinche El Relajo', de: 'Guachinche El Relajo' },
      description: {
        es: 'En las medianías de Tacoronte, este guachinche destaca por su carne a la brasa de leña y su vino blanco afrutado. El churrasco de cerdo es legendario. Solo efectivo, sin reservas y con horario limitado. El sitio perfecto para experimentar cómo comen los tinerfeños de verdad.',
        en: 'In the mid-heights of Tacoronte, this guachinche stands out for its wood-grilled meat and fruity white wine. The pork churrasco is legendary. Cash only, no reservations and limited hours. The perfect place to experience how locals really eat in Tenerife.',
        de: 'In den mittleren Höhenlagen von Tacoronte zeichnet sich dieses Guachinche durch sein holzgegrilltes Fleisch und fruchtigen Weißwein aus. Das Schweine-Churrasco ist legendär. Nur Barzahlung, keine Reservierung und begrenzte Öffnungszeiten. Der perfekte Ort um zu erleben, wie die Einheimischen wirklich essen.',
      },
      short_description: { es: 'Legendario churrasco a la brasa de leña', en: 'Legendary wood-grilled churrasco', de: 'Legendäres holzgegrilltes Churrasco' },
      image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&q=80',
      location: { es: 'Tacoronte', en: 'Tacoronte' },
      area_id: null,
      coordinates: { lat: 28.4760, lng: -16.4120 },
      rating: 4.7,
      review_count: 420,
      price_from: 6,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
  ])
  console.log('Guachinches added')

  // =============================================
  // CANARIAN CUISINE
  // =============================================
  console.log('Adding Canarian cuisine items...')
  await upsertItems([
    {
      subcategory_id: canarianCuisineId,
      slug: 'papas-arrugadas-con-mojo',
      name: { es: 'Papas Arrugadas con Mojo', en: 'Wrinkled Potatoes with Mojo', de: 'Runzelkartoffeln mit Mojo' },
      description: {
        es: 'El plato más icónico de Canarias: papas pequeñas cocidas con mucha sal hasta que la piel se arruga y forma una costra blanca. Se sirven con mojo rojo (pimentón, ajo, comino) y mojo verde (cilantro o perejil). Las encuentras en cualquier restaurante canario, pero las mejores se sirven en los guachinches del norte.',
        en: 'The most iconic Canarian dish: small potatoes boiled with lots of salt until the skin wrinkles and forms a white crust. Served with red mojo (paprika, garlic, cumin) and green mojo (coriander or parsley). Found in any Canarian restaurant, but the best are served in the guachinches of the north.',
        de: 'Das ikonischste kanarische Gericht: kleine Kartoffeln in viel Salz gekocht, bis die Schale schrumpelt und eine weiße Kruste bildet. Serviert mit rotem Mojo (Paprika, Knoblauch, Kreuzkümmel) und grünem Mojo (Koriander oder Petersilie). In jedem kanarischen Restaurant zu finden, aber die besten gibt es in den Guachinches im Norden.',
      },
      short_description: { es: 'El plato más emblemático de Canarias', en: 'The most emblematic Canarian dish', de: 'Das kultigste kanarische Gericht' },
      image: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=800&q=80',
      location: { es: 'Toda la isla', en: 'Whole island' },
      area_id: null,
      rating: 4.9,
      review_count: 2100,
      price_from: 4,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: canarianCuisineId,
      slug: 'gofio',
      name: { es: 'Gofio', en: 'Gofio', de: 'Gofio' },
      description: {
        es: 'Harina de cereales tostados (trigo, millo o mezcla) heredada de los guanches, los aborígenes canarios. Se usa de mil formas: escaldado en caldo de pescado, amasado con miel y almendras como postre (mousse de gofio), o simplemente espolvoreado. El Gofio La Molineta es de los más apreciados. Pruébalo en el Mercado de La Laguna.',
        en: 'Toasted cereal flour (wheat, corn or blend) inherited from the Guanches, the Canarian aborigines. Used in a thousand ways: scalded in fish broth, kneaded with honey and almonds as dessert (gofio mousse), or simply sprinkled. Gofio La Molineta is among the most prized. Try it at La Laguna Market.',
        de: 'Geröstetes Getreidemehl (Weizen, Mais oder Mischung), geerbt von den Guanchen, den kanarischen Ureinwohnern. Auf tausend Arten verwendet: in Fischbrühe blanchiert, mit Honig und Mandeln als Dessert (Gofio-Mousse) geknetet oder einfach darübergestreut. Gofio La Molineta gehört zu den geschätztesten. Probieren Sie es auf dem Markt von La Laguna.',
      },
      short_description: { es: 'Harina ancestral de los guanches', en: 'Ancestral flour from the Guanches', de: 'Uraltes Mehl der Guanchen' },
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
      location: { es: 'Toda la isla', en: 'Whole island' },
      area_id: null,
      rating: 4.4,
      review_count: 680,
      price_from: 3,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: canarianCuisineId,
      slug: 'sancocho-canario',
      name: { es: 'Sancocho Canario', en: 'Canarian Sancocho', de: 'Kanarischer Sancocho' },
      description: {
        es: 'Plato tradicional de pescado salado (cherne o corvina) cocido con papas, batatas y gofio escaldado, servido con mojo verde. Es el plato estrella de las fiestas canarias, especialmente en Semana Santa y Viernes Santo. Los mejores sancochos se encuentran en restaurantes de la costa norte como en Garachico y San Juan de la Rambla.',
        en: 'Traditional dish of salted fish (wreckfish or corvina) boiled with potatoes, sweet potatoes and scalded gofio, served with green mojo. The star dish of Canarian festivals, especially during Easter and Good Friday. The best sancochos are found in north coast restaurants in Garachico and San Juan de la Rambla.',
        de: 'Traditionelles Gericht aus gesalzenem Fisch (Wrackbarsch oder Corvina), gekocht mit Kartoffeln, Süßkartoffeln und blanchiertem Gofio, serviert mit grünem Mojo. Das Hauptgericht kanarischer Feste, besonders zu Ostern und Karfreitag. Die besten Sancochos finden sich in Restaurants an der Nordküste wie in Garachico und San Juan de la Rambla.',
      },
      short_description: { es: 'Plato tradicional de pescado con gofio', en: 'Traditional fish dish with gofio', de: 'Traditionelles Fischgericht mit Gofio' },
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
      location: { es: 'Costa norte de Tenerife', en: 'North coast of Tenerife' },
      area_id: null,
      rating: 4.6,
      review_count: 430,
      price_from: 12,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: canarianCuisineId,
      slug: 'queso-asado-con-mojo',
      name: { es: 'Queso Asado con Mojo', en: 'Grilled Cheese with Mojo', de: 'Gegrillter Käse mit Mojo' },
      description: {
        es: 'Queso de cabra o mezcla canario a la plancha, servido con mojo rojo o mojo de palma (con miel de palma gomera). Los quesos de Tenerife han ganado premios mundiales. Prueba el queso ahumado de Arico o el queso de Benijos. Lo encontrarás como entrante en prácticamente todos los restaurantes canarios.',
        en: 'Grilled Canarian goat or mixed cheese, served with red mojo or palm mojo (with La Gomera palm honey). Tenerife cheeses have won world awards. Try the smoked cheese from Arico or the Benijos cheese. You will find it as a starter in practically every Canarian restaurant.',
        de: 'Gegrillter kanarischer Ziegen- oder Mischkäse, serviert mit rotem Mojo oder Palmenhonig-Mojo (mit Palmenhonig aus La Gomera). Teneriffas Käse hat Weltpreise gewonnen. Probieren Sie den Räucherkäse aus Arico oder den Benijos-Käse. Als Vorspeise in praktisch jedem kanarischen Restaurant zu finden.',
      },
      short_description: { es: 'Queso canario a la plancha con mojo', en: 'Grilled Canarian cheese with mojo', de: 'Gegrillter kanarischer Käse mit Mojo' },
      image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80',
      location: { es: 'Toda la isla', en: 'Whole island' },
      area_id: null,
      rating: 4.7,
      review_count: 890,
      price_from: 6,
      currency: 'EUR',
      bookable: false,
      featured: true,
      sort_order: 4,
      visible: true,
    },
  ])
  console.log('Canarian cuisine items added')

  // =============================================
  // WINE TASTING
  // =============================================
  console.log('Adding wine tasting items...')
  await upsertItems([
    {
      subcategory_id: wineTastingId,
      slug: 'bodegas-monje',
      name: { es: 'Bodegas Monje', en: 'Monje Winery', de: 'Weingut Monje' },
      description: {
        es: 'Bodega familiar fundada en 1956 en El Sauzal con vistas espectaculares al Teide y al mar. Ofrece visitas guiadas con cata de vinos, maridaje con quesos canarios y un restaurante con cocina canaria moderna. Sus vinos tintos listán negro y malvasía aromática son excepcionales. Una de las bodegas más visitadas de Tenerife.',
        en: 'Family winery founded in 1956 in El Sauzal with spectacular views of Teide and the sea. Offers guided tours with wine tasting, pairing with Canarian cheeses and a restaurant with modern Canarian cuisine. Their listán negro red wines and aromatic malvasia are exceptional. One of the most visited wineries in Tenerife.',
        de: 'Familienweingut, gegründet 1956 in El Sauzal, mit spektakulärem Blick auf den Teide und das Meer. Bietet Führungen mit Weinprobe, Verkostung mit kanarischem Käse und ein Restaurant mit moderner kanarischer Küche. Ihre Listán-Negro-Rotweine und aromatische Malvasía sind außergewöhnlich. Eines der meistbesuchten Weingüter Teneriffas.',
      },
      short_description: { es: 'Bodega familiar con vistas al Teide', en: 'Family winery with Teide views', de: 'Familienweingut mit Teide-Blick' },
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
      location: { es: 'El Sauzal', en: 'El Sauzal' },
      area_id: null,
      coordinates: { lat: 28.4750, lng: -16.4280 },
      rating: 4.7,
      review_count: 620,
      price_from: 15,
      currency: 'EUR',
      duration: '1.5-2 hours',
      bookable: true,
      booking_url: 'https://www.bodegasmonje.com',
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: wineTastingId,
      slug: 'bodegas-reveron',
      name: { es: 'Bodegas Reverón', en: 'Reverón Winery', de: 'Weingut Reverón' },
      description: {
        es: 'Bodega artesanal en las medianías del sur de Tenerife (Vilaflor, el pueblo más alto de España). Produce vinos de altura con uvas cultivadas a más de 1.400 metros sobre el nivel del mar. Catas privadas con el enólogo, visita a los viñedos y degustación de productos locales. Vinos minerales y frescos únicos.',
        en: 'Artisan winery in the mid-heights of southern Tenerife (Vilaflor, the highest village in Spain). Produces altitude wines with grapes grown above 1,400 meters. Private tastings with the winemaker, vineyard visit and local product tasting. Unique mineral and fresh wines.',
        de: 'Handwerkliches Weingut in den mittleren Höhen Südteneriffas (Vilaflor, das höchstgelegene Dorf Spaniens). Produziert Höhenweine mit Trauben, die über 1.400 Metern angebaut werden. Private Verkostungen mit dem Winzer, Weinbergbesuch und Verkostung lokaler Produkte. Einzigartige mineralische und frische Weine.',
      },
      short_description: { es: 'Vinos de altura en el pueblo más alto de España', en: 'Altitude wines in Spain\'s highest village', de: 'Höhenweine im höchsten Dorf Spaniens' },
      image: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&q=80',
      location: { es: 'Vilaflor', en: 'Vilaflor' },
      area_id: null,
      coordinates: { lat: 28.1580, lng: -16.6340 },
      rating: 4.6,
      review_count: 280,
      price_from: 20,
      currency: 'EUR',
      duration: '1.5 hours',
      bookable: true,
      featured: false,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: wineTastingId,
      slug: 'casa-del-vino-la-baranda',
      name: { es: 'Casa del Vino La Baranda', en: 'La Baranda Wine House', de: 'Weinhaus La Baranda' },
      description: {
        es: 'Museo del vino ubicado en una hacienda del siglo XVII en El Sauzal. Espacio dedicado a la historia y cultura del vino en Tenerife con sala de catas donde puedes probar vinos de las 5 denominaciones de origen de la isla. Tienda con todos los vinos canarios, miel y quesos. Entrada casi gratuita y catas desde 5 euros.',
        en: 'Wine museum housed in a 17th-century estate in El Sauzal. Space dedicated to the history and culture of wine in Tenerife with a tasting room where you can try wines from all 5 designations of origin on the island. Shop with all Canarian wines, honey and cheeses. Nearly free entry and tastings from 5 euros.',
        de: 'Weinmuseum in einem Landgut aus dem 17. Jahrhundert in El Sauzal. Raum gewidmet der Geschichte und Kultur des Weins auf Teneriffa mit Verkostungsraum, wo Sie Weine aller 5 Herkunftsbezeichnungen der Insel probieren können. Laden mit allen kanarischen Weinen, Honig und Käse. Fast kostenloser Eintritt und Verkostungen ab 5 Euro.',
      },
      short_description: { es: 'Museo del vino con catas desde 5 euros', en: 'Wine museum with tastings from 5 euros', de: 'Weinmuseum mit Verkostungen ab 5 Euro' },
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=800&q=80',
      location: { es: 'El Sauzal', en: 'El Sauzal' },
      area_id: null,
      coordinates: { lat: 28.4730, lng: -16.4320 },
      rating: 4.4,
      review_count: 480,
      price_from: 5,
      currency: 'EUR',
      duration: '1-2 hours',
      bookable: false,
      featured: true,
      sort_order: 3,
      visible: true,
    },
  ])
  console.log('Wine tasting items added')

  // =============================================
  // WATER SPORTS
  // =============================================
  console.log('Adding water sports...')
  await upsertItems([
    {
      subcategory_id: waterSportsId,
      slug: 'surf-las-americas',
      name: { es: 'Surf en Playa de las Américas', en: 'Surfing in Playa de las Américas', de: 'Surfen in Playa de las Américas' },
      description: {
        es: 'La zona de La Izquierda en Playa de las Américas es el spot de surf más famoso de Tenerife, con una ola izquierda larga y consistente. Varias escuelas ofrecen clases para principiantes (desde 35 euros) con equipos incluidos. Los más avanzados pueden alquilar tabla y neopreno. Mejor época: octubre a marzo.',
        en: 'La Izquierda in Playa de las Américas is Tenerife\'s most famous surf spot, with a long and consistent left-hand wave. Several schools offer beginner classes (from 35 euros) with equipment included. Advanced surfers can rent boards and wetsuits. Best season: October to March.',
        de: 'La Izquierda in Playa de las Américas ist Teneriffas berühmtester Surfspot mit einer langen und konstanten Linkswelle. Mehrere Schulen bieten Anfängerkurse (ab 35 Euro) mit Ausrüstung an. Fortgeschrittene können Brett und Neoprenanzug mieten. Beste Saison: Oktober bis März.',
      },
      short_description: { es: 'Clases y alquiler de surf en el sur', en: 'Surf lessons and rental in the south', de: 'Surfkurse und -verleih im Süden' },
      image: 'https://images.unsplash.com/photo-1502680390548-bdbac40e4a9f?w=800&q=80',
      location: { es: 'Playa de las Américas', en: 'Playa de las Américas' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0560, lng: -16.7270 },
      rating: 4.6,
      review_count: 540,
      price_from: 35,
      currency: 'EUR',
      duration: '2 hours',
      bookable: true,
      featured: true,
      sort_order: 1,
      visible: true,
    },
    {
      subcategory_id: waterSportsId,
      slug: 'buceo-los-gigantes',
      name: { es: 'Buceo en Los Gigantes', en: 'Diving at Los Gigantes', de: 'Tauchen bei Los Gigantes' },
      description: {
        es: 'Inmersiones espectaculares junto a los acantilados de Los Gigantes que caen verticalmente 600 metros al mar. Visibilidad excepcional (30-40 metros), tortugas marinas, rayas, mantas y una rica vida submarina. Centros de buceo ofrecen bautismos para principiantes y salidas para buceadores certificados. Uno de los mejores puntos de buceo de Canarias.',
        en: 'Spectacular dives alongside the Los Gigantes cliffs that drop vertically 600 meters into the sea. Exceptional visibility (30-40 meters), sea turtles, rays, mantas and rich marine life. Dive centers offer discovery dives for beginners and trips for certified divers. One of the best dive sites in the Canaries.',
        de: 'Spektakuläre Tauchgänge an den Klippen von Los Gigantes, die 600 Meter senkrecht ins Meer fallen. Außergewöhnliche Sicht (30-40 Meter), Meeresschildkröten, Rochen, Mantas und reiches Meeresleben. Tauchzentren bieten Schnuppertauchen für Anfänger und Ausfahrten für zertifizierte Taucher. Einer der besten Tauchplätze der Kanaren.',
      },
      short_description: { es: 'Buceo junto a los acantilados de 600m', en: 'Diving alongside 600m cliffs', de: 'Tauchen an 600m hohen Klippen' },
      image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
      location: { es: 'Los Gigantes', en: 'Los Gigantes' },
      area_id: losGigantes,
      coordinates: { lat: 28.2470, lng: -16.8420 },
      rating: 4.8,
      review_count: 380,
      price_from: 55,
      currency: 'EUR',
      duration: '3 hours',
      bookable: true,
      featured: true,
      sort_order: 2,
      visible: true,
    },
    {
      subcategory_id: waterSportsId,
      slug: 'kayak-los-gigantes',
      name: { es: 'Kayak en Los Gigantes', en: 'Kayaking at Los Gigantes', de: 'Kajakfahren bei Los Gigantes' },
      description: {
        es: 'Recorre en kayak la base de los impresionantes acantilados de Los Gigantes, con paredes verticales de 600 metros sobre ti. Ruta guiada de unas 2 horas con parada para snorkel en cuevas marinas. Posibilidad de avistar tortugas y delfines. No se necesita experiencia previa. Incluye equipo, guía y fotos.',
        en: 'Kayak along the base of the impressive Los Gigantes cliffs, with 600-meter vertical walls above you. Guided 2-hour route with snorkeling stop in sea caves. Possibility of spotting turtles and dolphins. No prior experience needed. Equipment, guide and photos included.',
        de: 'Paddeln Sie mit dem Kajak entlang der beeindruckenden Klippen von Los Gigantes mit 600 Meter hohen senkrechten Wänden über Ihnen. Geführte 2-stündige Route mit Schnorchelstopp in Meereshöhlen. Möglichkeit, Schildkröten und Delfine zu sehen. Keine Vorkenntnisse nötig. Ausrüstung, Guide und Fotos inklusive.',
      },
      short_description: { es: 'Kayak y snorkel bajo los acantilados', en: 'Kayak and snorkel beneath the cliffs', de: 'Kajak und Schnorcheln unter den Klippen' },
      image: 'https://images.unsplash.com/photo-1472745942893-4b9f730c7668?w=800&q=80',
      location: { es: 'Los Gigantes', en: 'Los Gigantes' },
      area_id: losGigantes,
      coordinates: { lat: 28.2450, lng: -16.8400 },
      rating: 4.7,
      review_count: 620,
      price_from: 40,
      currency: 'EUR',
      duration: '2-3 hours',
      bookable: true,
      featured: true,
      sort_order: 3,
      visible: true,
    },
    {
      subcategory_id: waterSportsId,
      slug: 'jet-ski-costa-adeje',
      name: { es: 'Jet Ski en Costa Adeje', en: 'Jet Ski in Costa Adeje', de: 'Jet Ski in Costa Adeje' },
      description: {
        es: 'Alquila un jet ski y recorre la costa sur de Tenerife a toda velocidad. Circuitos guiados de 20 a 60 minutos desde Puerto Colón pasando por las playas del Duque y Fañabé. Para mayores de 18 años con o sin licencia (circuito cerrado o mar abierto). Sensaciones fuertes con vistas a La Gomera en el horizonte.',
        en: 'Rent a jet ski and cruise the southern coast of Tenerife at full speed. Guided circuits from 20 to 60 minutes from Puerto Colón past Duque and Fañabé beaches. For ages 18+ with or without license (closed circuit or open sea). Thrills with views of La Gomera on the horizon.',
        de: 'Mieten Sie einen Jet Ski und rasen Sie die Südküste Teneriffas entlang. Geführte Rundfahrten von 20 bis 60 Minuten ab Puerto Colón vorbei an den Stränden El Duque und Fañabé. Ab 18 Jahren mit oder ohne Lizenz (geschlossener Kurs oder offenes Meer). Nervenkitzel mit Blick auf La Gomera am Horizont.',
      },
      short_description: { es: 'Adrenalina sobre el agua en la costa sur', en: 'Adrenaline on the water on the south coast', de: 'Adrenalin auf dem Wasser an der Südküste' },
      image: 'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=800&q=80',
      location: { es: 'Puerto Colón, Costa Adeje', en: 'Puerto Colón, Costa Adeje' },
      area_id: costaAdeje,
      coordinates: { lat: 28.0750, lng: -16.7350 },
      rating: 4.5,
      review_count: 310,
      price_from: 60,
      currency: 'EUR',
      duration: '20-60 min',
      bookable: true,
      featured: false,
      sort_order: 4,
      visible: true,
    },
  ])
  console.log('Water sports added')

  console.log('\nAll content added successfully!')
}

main().catch((err) => {
  console.error('Error:', err)
  process.exit(1)
})
