-- Seed initial categories and areas

-- ============================================
-- AREAS
-- ============================================
insert into public.areas (slug, name, description, region) values
  ('costa-adeje', '{"es":"Costa Adeje","en":"Costa Adeje","de":"Costa Adeje","fr":"Costa Adeje","ru":"Коста Адехе","it":"Costa Adeje"}', '{"es":"La zona turística más exclusiva del sur de Tenerife, con playas de arena dorada, resorts de lujo y una animada vida nocturna.","en":"The most exclusive tourist area in southern Tenerife, with golden sand beaches, luxury resorts and vibrant nightlife.","de":"Das exklusivste Touristengebiet im Süden Teneriffas mit goldenen Sandstränden, Luxusresorts und pulsierendem Nachtleben."}', 'south'),
  ('los-cristianos', '{"es":"Los Cristianos","en":"Los Cristianos","de":"Los Cristianos","fr":"Los Cristianos","ru":"Лос Кристианос","it":"Los Cristianos"}', '{"es":"Antiguo pueblo pesquero convertido en un animado centro turístico con playas familiares y un encantador paseo marítimo.","en":"Former fishing village turned lively tourist hub with family-friendly beaches and a charming promenade.","de":"Ehemaliges Fischerdorf, heute ein lebhaftes Touristenzentrum mit familienfreundlichen Stränden."}', 'south'),
  ('puerto-de-la-cruz', '{"es":"Puerto de la Cruz","en":"Puerto de la Cruz","de":"Puerto de la Cruz","fr":"Puerto de la Cruz","ru":"Пуэрто де ла Крус","it":"Puerto de la Cruz"}', '{"es":"La joya del norte de Tenerife, con su casco histórico, jardines botánicos y el icónico Lago Martiánez.","en":"The jewel of northern Tenerife, with its historic old town, botanical gardens and iconic Lago Martiánez.","de":"Das Juwel des Nordens von Teneriffa mit historischer Altstadt, botanischen Gärten und dem ikonischen Lago Martiánez."}', 'north'),
  ('santa-cruz', '{"es":"Santa Cruz de Tenerife","en":"Santa Cruz de Tenerife","de":"Santa Cruz de Teneriffa","fr":"Santa Cruz de Tenerife","ru":"Санта Крус де Тенерифе","it":"Santa Cruz de Tenerife"}', '{"es":"La capital de la isla, centro cultural y comercial con arquitectura impresionante y el famoso Carnaval.","en":"The island capital, cultural and commercial center with impressive architecture and the famous Carnival.","de":"Die Inselhauptstadt, kulturelles und kommerzielles Zentrum mit beeindruckender Architektur und dem berühmten Karneval."}', 'central'),
  ('la-laguna', '{"es":"San Cristóbal de La Laguna","en":"San Cristóbal de La Laguna","de":"San Cristóbal de La Laguna","fr":"San Cristóbal de La Laguna","ru":"Ла Лагуна","it":"San Cristóbal de La Laguna"}', '{"es":"Ciudad Patrimonio de la Humanidad por la UNESCO, universidad histórica y el centro cultural de Tenerife.","en":"UNESCO World Heritage city, historic university town and the cultural heart of Tenerife.","de":"UNESCO-Weltkulturerbe, historische Universitätsstadt und kulturelles Herz Teneriffas."}', 'north'),
  ('los-gigantes', '{"es":"Los Gigantes","en":"Los Gigantes","de":"Los Gigantes","fr":"Los Gigantes","ru":"Лос Гигантес","it":"Los Gigantes"}', '{"es":"Espectaculares acantilados de hasta 600m sobre el mar, avistamiento de ballenas y puestas de sol inolvidables.","en":"Spectacular cliffs rising 600m above the sea, whale watching and unforgettable sunsets.","de":"Spektakuläre Klippen bis zu 600m über dem Meer, Walbeobachtung und unvergessliche Sonnenuntergänge."}', 'west'),
  ('teide', '{"es":"Parque Nacional del Teide","en":"Teide National Park","de":"Teide-Nationalpark","fr":"Parc National du Teide","ru":"Национальный парк Тейде","it":"Parco Nazionale del Teide"}', '{"es":"El volcán más alto de España y Patrimonio de la Humanidad, con paisajes lunares y las mejores estrellas de Europa.","en":"Spain''s highest volcano and UNESCO World Heritage site, with lunar landscapes and Europe''s best stargazing.","de":"Spaniens höchster Vulkan und UNESCO-Welterbe mit Mondlandschaften und Europas bestem Sternenhimmel."}', 'central'),
  ('anaga', '{"es":"Macizo de Anaga","en":"Anaga Mountains","de":"Anaga-Gebirge","fr":"Massif d''Anaga","ru":"Горы Анага","it":"Monti di Anaga"}', '{"es":"Reserva de la Biosfera con bosques de laurisilva, senderos espectaculares y playas remotas.","en":"Biosphere Reserve with ancient laurel forests, spectacular hiking trails and remote beaches.","de":"Biosphärenreservat mit uralten Lorbeerwäldern, spektakulären Wanderwegen und abgelegenen Stränden."}', 'north');

-- ============================================
-- CATEGORIES
-- ============================================
insert into public.categories (slug, icon, name, description, sort_order) values
  ('experiences', 'Camera', '{"es":"Experiencias","en":"Experiences","de":"Erlebnisse","fr":"Expériences","ru":"Развлечения","it":"Esperienze"}', '{"es":"Las mejores actividades y excursiones en Tenerife","en":"The best activities and excursions in Tenerife","de":"Die besten Aktivitäten und Ausflüge auf Teneriffa","fr":"Les meilleures activités et excursions à Tenerife","ru":"Лучшие развлечения и экскурсии на Тенерифе","it":"Le migliori attività ed escursioni a Tenerife"}', 1),
  ('beaches', 'Waves', '{"es":"Playas","en":"Beaches","de":"Strände","fr":"Plages","ru":"Пляжи","it":"Spiagge"}', '{"es":"Más de 150 playas de arena negra volcánica y dorada","en":"Over 150 beaches of volcanic black and golden sand","de":"Über 150 Strände mit schwarzem Vulkan- und goldenem Sand","fr":"Plus de 150 plages de sable noir volcanique et doré","ru":"Более 150 пляжей с вулканическим чёрным и золотым песком","it":"Oltre 150 spiagge di sabbia nera vulcanica e dorata"}', 2),
  ('culture', 'Landmark', '{"es":"Cultura e Historia","en":"Culture & History","de":"Kultur & Geschichte","fr":"Culture & Histoire","ru":"Культура и История","it":"Cultura e Storia"}', '{"es":"Pueblos históricos, museos, tradiciones y patrimonio guanche","en":"Historic towns, museums, traditions and Guanche heritage","de":"Historische Städte, Museen, Traditionen und Guanchen-Erbe","fr":"Villes historiques, musées, traditions et patrimoine guanche","ru":"Исторические города, музеи, традиции и наследие гуанчей","it":"Città storiche, musei, tradizioni e patrimonio guanche"}', 3),
  ('nature', 'TreePine', '{"es":"Naturaleza y Senderismo","en":"Nature & Hiking","de":"Natur & Wandern","fr":"Nature & Randonnée","ru":"Природа и Походы","it":"Natura e Trekking"}', '{"es":"Parque Nacional del Teide, bosques de laurisilva, rutas de senderismo","en":"Teide National Park, laurel forests, hiking trails","de":"Teide-Nationalpark, Lorbeerwälder, Wanderwege","fr":"Parc National du Teide, forêts de lauriers, sentiers de randonnée","ru":"Национальный парк Тейде, лавровые леса, пешеходные маршруты","it":"Parco Nazionale del Teide, foreste di alloro, sentieri escursionistici"}', 4),
  ('food', 'Utensils', '{"es":"Gastronomía","en":"Food & Drink","de":"Essen & Trinken","fr":"Gastronomie","ru":"Еда и Напитки","it":"Gastronomia"}', '{"es":"Restaurantes, guachinches, vinos locales y cocina canaria","en":"Restaurants, guachinches, local wines and Canarian cuisine","de":"Restaurants, Guachinches, lokale Weine und kanarische Küche","fr":"Restaurants, guachinches, vins locaux et cuisine canarienne","ru":"Рестораны, гуачинчес, местные вина и канарская кухня","it":"Ristoranti, guachinches, vini locali e cucina canaria"}', 5),
  ('nightlife', 'Music', '{"es":"Vida Nocturna","en":"Nightlife","de":"Nachtleben","fr":"Vie Nocturne","ru":"Ночная Жизнь","it":"Vita Notturna"}', '{"es":"Bares, discotecas, música en vivo y espectáculos","en":"Bars, clubs, live music and shows","de":"Bars, Clubs, Livemusik und Shows","fr":"Bars, clubs, musique live et spectacles","ru":"Бары, клубы, живая музыка и шоу","it":"Bar, club, musica dal vivo e spettacoli"}', 6),
  ('shopping', 'ShoppingBag', '{"es":"Compras","en":"Shopping","de":"Einkaufen","fr":"Shopping","ru":"Шопинг","it":"Shopping"}', '{"es":"Centros comerciales, mercados locales y productos artesanales","en":"Shopping centers, local markets and artisan products","de":"Einkaufszentren, lokale Märkte und handwerkliche Produkte","fr":"Centres commerciaux, marchés locaux et produits artisanaux","ru":"Торговые центры, местные рынки и ремесленные изделия","it":"Centri commerciali, mercati locali e prodotti artigianali"}', 7),
  ('family', 'Baby', '{"es":"Familia","en":"Family Fun","de":"Familienspaß","fr":"Famille","ru":"Для Семьи","it":"Famiglia"}', '{"es":"Parques temáticos, parques acuáticos, zoológicos y actividades para niños","en":"Theme parks, water parks, zoos and activities for children","de":"Themenparks, Wasserparks, Zoos und Aktivitäten für Kinder","fr":"Parcs à thème, parcs aquatiques, zoos et activités pour enfants","ru":"Тематические парки, аквапарки, зоопарки и развлечения для детей","it":"Parchi tematici, parchi acquatici, zoo e attività per bambini"}', 8),
  ('wellness', 'Sparkles', '{"es":"Bienestar y Spa","en":"Wellness & Spa","de":"Wellness & Spa","fr":"Bien-être & Spa","ru":"Велнес и Спа","it":"Benessere e Spa"}', '{"es":"Spas, retiros de yoga, terapias holísticas y relax","en":"Spas, yoga retreats, holistic therapies and relaxation","de":"Spas, Yoga-Retreats, ganzheitliche Therapien und Entspannung","fr":"Spas, retraites de yoga, thérapies holistiques et relaxation","ru":"Спа, йога-ретриты, холистические терапии и релаксация","it":"Spa, ritiri yoga, terapie olistiche e relax"}', 9);

-- ============================================
-- SAMPLE SUBCATEGORIES
-- ============================================
insert into public.subcategories (category_id, slug, name, description, sort_order) values
  -- Experiences
  ((select id from categories where slug = 'experiences'), 'top-experiences', '{"es":"Top Experiencias","en":"Top Experiences","de":"Top-Erlebnisse","fr":"Top Expériences","ru":"Лучшие Развлечения","it":"Top Esperienze"}', '{"es":"Las experiencias más populares y mejor valoradas","en":"The most popular and highest rated experiences","de":"Die beliebtesten und am besten bewerteten Erlebnisse"}', 1),
  ((select id from categories where slug = 'experiences'), 'whale-watching', '{"es":"Avistamiento de Ballenas","en":"Whale & Dolphin Watching","de":"Wal- & Delfinbeobachtung","fr":"Observation de Baleines","ru":"Наблюдение за Китами","it":"Avvistamento Balene"}', '{"es":"Excursiones en barco para ver ballenas y delfines en su hábitat natural","en":"Boat trips to see whales and dolphins in their natural habitat","de":"Bootsausflüge zur Beobachtung von Walen und Delfinen in ihrem natürlichen Lebensraum"}', 2),
  ((select id from categories where slug = 'experiences'), 'teide-tours', '{"es":"Excursiones al Teide","en":"Teide Tours","de":"Teide-Touren","fr":"Excursions au Teide","ru":"Экскурсии на Тейде","it":"Tour del Teide"}', '{"es":"Visitas al volcán Teide, observación de estrellas y rutas de senderismo","en":"Visits to Mount Teide, stargazing and hiking routes","de":"Besuche am Vulkan Teide, Sternebeobachtung und Wanderrouten"}', 3),
  ((select id from categories where slug = 'experiences'), 'water-sports', '{"es":"Deportes Acuáticos","en":"Water Sports","de":"Wassersport","fr":"Sports Nautiques","ru":"Водные Виды Спорта","it":"Sport Acquatici"}', '{"es":"Surf, buceo, kayak, jet ski y más actividades acuáticas","en":"Surfing, diving, kayaking, jet ski and more water activities","de":"Surfen, Tauchen, Kajakfahren, Jet-Ski und weitere Wasseraktivitäten"}', 4),
  -- Beaches
  ((select id from categories where slug = 'beaches'), 'best-beaches', '{"es":"Mejores Playas","en":"Best Beaches","de":"Beste Strände","fr":"Meilleures Plages","ru":"Лучшие Пляжи","it":"Migliori Spiagge"}', '{"es":"Las playas más bonitas y populares de Tenerife","en":"The most beautiful and popular beaches in Tenerife","de":"Die schönsten und beliebtesten Strände Teneriffas"}', 1),
  ((select id from categories where slug = 'beaches'), 'north-beaches', '{"es":"Playas del Norte","en":"North Beaches","de":"Nordstrände","fr":"Plages du Nord","ru":"Пляжи Севера","it":"Spiagge del Nord"}', '{"es":"Playas salvajes y naturales del norte de Tenerife","en":"Wild and natural beaches of northern Tenerife","de":"Wilde und natürliche Strände im Norden Teneriffas"}', 2),
  ((select id from categories where slug = 'beaches'), 'south-beaches', '{"es":"Playas del Sur","en":"South Beaches","de":"Südstrände","fr":"Plages du Sud","ru":"Пляжи Юга","it":"Spiagge del Sud"}', '{"es":"Playas de arena dorada y aguas tranquilas del sur","en":"Golden sand beaches and calm waters of the south","de":"Goldene Sandstrände und ruhiges Wasser im Süden"}', 3),
  ((select id from categories where slug = 'beaches'), 'family-beaches', '{"es":"Playas Familiares","en":"Family Beaches","de":"Familienstrände","fr":"Plages Familiales","ru":"Семейные Пляжи","it":"Spiagge per Famiglie"}', '{"es":"Playas seguras y cómodas para ir con niños","en":"Safe and comfortable beaches for families with children","de":"Sichere und komfortable Strände für Familien mit Kindern"}', 4),
  -- Nature
  ((select id from categories where slug = 'nature'), 'teide-national-park', '{"es":"Parque Nacional del Teide","en":"Teide National Park","de":"Teide-Nationalpark","fr":"Parc National du Teide","ru":"Национальный Парк Тейде","it":"Parco Nazionale del Teide"}', '{"es":"El parque más visitado de España con paisajes volcánicos únicos","en":"Spain''s most visited park with unique volcanic landscapes","de":"Spaniens meistbesuchter Park mit einzigartigen Vulkanlandschaften"}', 1),
  ((select id from categories where slug = 'nature'), 'hiking-trails', '{"es":"Rutas de Senderismo","en":"Hiking Trails","de":"Wanderwege","fr":"Sentiers de Randonnée","ru":"Пешеходные Маршруты","it":"Sentieri Escursionistici"}', '{"es":"Las mejores rutas para caminar por Tenerife","en":"The best trails for hiking in Tenerife","de":"Die besten Wanderwege auf Teneriffa"}', 2),
  ((select id from categories where slug = 'nature'), 'natural-pools', '{"es":"Piscinas Naturales","en":"Natural Pools","de":"Natürliche Pools","fr":"Piscines Naturelles","ru":"Природные Бассейны","it":"Piscine Naturali"}', '{"es":"Piscinas formadas en la roca volcánica por el mar","en":"Pools formed in volcanic rock by the sea","de":"In Vulkangestein geformte Pools am Meer"}', 3),
  -- Food
  ((select id from categories where slug = 'food'), 'best-restaurants', '{"es":"Mejores Restaurantes","en":"Best Restaurants","de":"Beste Restaurants","fr":"Meilleurs Restaurants","ru":"Лучшие Рестораны","it":"Migliori Ristoranti"}', '{"es":"Los restaurantes más recomendados de la isla","en":"The island''s most recommended restaurants","de":"Die empfehlenswertesten Restaurants der Insel"}', 1),
  ((select id from categories where slug = 'food'), 'guachinches', '{"es":"Guachinches","en":"Guachinches","de":"Guachinches","fr":"Guachinches","ru":"Гуачинчес","it":"Guachinches"}', '{"es":"Pequeños locales familiares donde se sirve comida casera canaria con vino propio","en":"Small family-run eateries serving homemade Canarian food with their own wine","de":"Kleine familiengeführte Lokale mit hausgemachter kanarischer Küche und eigenem Wein"}', 2),
  ((select id from categories where slug = 'food'), 'canarian-cuisine', '{"es":"Cocina Canaria","en":"Canarian Cuisine","de":"Kanarische Küche","fr":"Cuisine Canarienne","ru":"Канарская Кухня","it":"Cucina Canaria"}', '{"es":"Platos típicos, ingredientes locales y tradiciones gastronómicas","en":"Typical dishes, local ingredients and gastronomic traditions","de":"Typische Gerichte, lokale Zutaten und gastronomische Traditionen"}', 3),
  ((select id from categories where slug = 'food'), 'wine-tasting', '{"es":"Catas de Vino","en":"Wine Tasting","de":"Weinverkostung","fr":"Dégustation de Vin","ru":"Дегустация Вин","it":"Degustazione Vini"}', '{"es":"Bodegas locales, rutas del vino y catas en Tenerife","en":"Local wineries, wine routes and tastings in Tenerife","de":"Lokale Weingüter, Weinrouten und Verkostungen auf Teneriffa"}', 4);
